version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/ospf_route_summarization_policy/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/ospf_route_summarization_policy/actions/workflows/test.yml)

  # Terraform ACI OSPF Route Summarization module

  Manages OSPF route summarization policy

  Location in GUI:
  `Tenants` » `XXX` » `Policies` » `Protocol` » `OSPF` » `OSPF Route Summarization`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
